dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "HJzMrBMjJ9+H1UroodSLo0tiUrBytZQz1EqGykWqU/PcgwVjVSTPqvLmFkfPbIZm3on9GElblUQqXV3/J9X2UTu4a/ZmWL5v09Tk2O12jKGbFV71LtlDFvvIoy8DtIIfnE0r642wyu6ii3VVt1J6FI/oixNmF25S6DdWDaA+q3NWlA+MZEae3n1YuQmhkpgoMkWe6xC3H6Oxdo0XgTn0SfqfBES8IM+3hG4FCU6tYfOVoffVEUd1eq3J9W7aGfMQ4zTEAorwroyWuFRDbG+W+PK8uMUJpSDDzjq3271yJAFPtLlGL2f+JPZO5GUui1IW+VM4Ju9YhQ5MiYzQXpdIUKFtBQZr480PrmTL9hP0zZFJA/QkBYr6otyBvaDOEkM1Bv/I9v2EjiutfVKVP09FKIEMNASdCCvtJ6p+BS3r2a74MZNcFtqcjXPd8ROxrh49n6hrkt99jvwsybgTpsgayTxT0N6Pdd1ni6sAiQ3LtXo6vFCi2apJ1v1hBoOXRfNvIdq00inyQI/P3LNcQzXLTou63oh2Z+I7UJcQHnl0pc4pndQMQm4A+22fFUrXRByPJK2dZpd7l/PSIEl0reirzk3UIUw1qmJlZyabAmPJPzPjvodjbH3pH5mK0S050UNDXi6G1u+F91td5gMrXxq3sA4/GIp1RpyoovSrOzIZEf4="
    - secure: "P3gRgSFJNUfku81Yl61Fh5QbkH5E4ccFSv9zbwNwQQkTVNTXd3Zv5TVTjt/eXI/wM7PZnDrhWxz8y7D4J1vZjqvbIGnmXyjsm/jX83HTDt70aE/4N4oKCZcEr783H2xlXcUnrxPXW87vV4Bw/JU7EVF26jC1tAIrnfVUMfNxYMpxCi19S7Qg72nOGcNgDJbQj/Unl7UEmbEPV4POiytwF6oVDWLp+Ys8JjujeS9rCtd6vzKxBR08WLAlqG07SSLb98UxCZA+p+D7uFfQMOAkp91L9S+vXXn0FIDczmEEYaAnPRJYszDfaEr6aQSvIQVyaWVqLYBKuSFZpnXPqyczgtXgNVk1H01gRtXPjF18kAD8e/UT/n4x9YvsN7FRDr5mXO0wd/XPmbZ9D2ZrOqDNKNzFv3LdnzpWL1BJsgAbI/nhUqjz1WJ+WVUXDq6jNMegJOXGRia04D05XKBgW71ULmMZrKNufab1l9Hy2gEVpZ0AgUlSxRLNmvYLh1TZTS9Tp2ONHEBkVEFo3tbt7hP8MeTM/6sqwhhY27CGv9yfmEMBLNURDodaXAyUQEBBbCF6KLIkX+RoQsvho2+TZE1jxheY1MffL+MlWtmbVCpK46W7yeB1Gk+AptY7vJ5JsRa+RWrrwFEChfgymWJfIwPiFVRm947XAv6QirsWNJV9fqw="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
